# Generated by Django 4.2.4 on 2023-08-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='image',
            field=models.ImageField(blank=True, upload_to='leads_images/'),
        ),
    ]
